@Author:Vijay Kumar M N<br>
@Date: 2024-11-07<br>
@Last Modified by:Vijay Kumar M N<br>
@Last Modified: 2024-11-07<br>
@Title :Python Program to handle the data<br>

Classify the problems as supervised, unsupervised, reinforcement or semi supervised<br>
a. Spam filtering: Is an email spam or not -<b>Supervised Learning</b><br>
b. Given a list of customers and information about them, discover groups of similar<br>
users. This knowledge can then be used for targeted marketing - <b>Unsupervised Learning</b><br>
c. Robotics: A robot is in a maze, and it needs to find a way out.- <b>Reinforcement</b><br>
d. Training an AI for a complex game such as Civilization or Dota -<b> Semi-supervised Learning</b><br>
e. Anomaly detection: Given measurements from sensors in a manufacturing<br>
facility, identify anomalies, i.e. that something is wrong- <b>Unsupervised Learning</b><br>
f. Discover patterns in data such as whenever it rains, people tend to stay indoors.<br>
When it is hot, people buy more ice-cream.-<b>unsupervised Learning</b><br>
g. Given information about a house, predict its price- <b>Supervised Learning</b><br>
h. Netflix: Given a user and a movie, predict the rating the user is going to give to
the movie- <b>Supervervised Learning</b><br>    
i. Given an image, output which objects are present in the image- <b>supervised Learning</b><br>

In [124]:
#importing the libraries
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split

In [125]:
#reading the data
data=pd.read_csv("C:/Users/Admin/Downloads/data_preprocessing.csv")
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [126]:
# Step 1: Handle missing data
data['Age'].fillna(data['Age'].mean(),inplace=True)
data['Age']=data['Age'].astype(int)
data['Salary'].fillna(data['Salary'].mean(), inplace=True)
print(data)

   Country  Age        Salary Purchased
0   France   44  72000.000000        No
1    Spain   27  48000.000000       Yes
2  Germany   30  54000.000000        No
3    Spain   38  61000.000000        No
4  Germany   40  63777.777778       Yes
5   France   35  58000.000000       Yes
6    Spain   38  52000.000000        No
7   France   48  79000.000000       Yes
8  Germany   50  83000.000000        No
9   France   37  67000.000000       Yes


C:\Users\Admin\AppData\Local\Temp\ipykernel_18772\3117559118.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(),inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18772\3117559118.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For 

In [127]:
# Step 2: Convert categorical data
# One-hot encoding for 'Country'
data = pd.get_dummies(data, columns=['Country'], drop_first=True)

# Label encoding for 'Purchased'
label_encoder = LabelEncoder()
data['Purchased'] = label_encoder.fit_transform(data['Purchased'])
print(data)

   Age        Salary  Purchased  Country_Germany  Country_Spain
0   44  72000.000000          0            False          False
1   27  48000.000000          1            False           True
2   30  54000.000000          0             True          False
3   38  61000.000000          0            False           True
4   40  63777.777778          1             True          False
5   35  58000.000000          1            False          False
6   38  52000.000000          0            False           True
7   48  79000.000000          1            False          False
8   50  83000.000000          0             True          False
9   37  67000.000000          1            False          False


In [128]:
# Step 3: Split the dataset
X = data.drop('Purchased', axis=1)  # Features
y = data['Purchased']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print("Train Data")
print(X_train)
print("Test Data")
print(X_test)

Train Data
   Age        Salary  Country_Germany  Country_Spain
0   44  72000.000000            False          False
7   48  79000.000000            False          False
2   30  54000.000000             True          False
9   37  67000.000000            False          False
4   40  63777.777778             True          False
3   38  61000.000000            False           True
6   38  52000.000000            False           True
Test Data
   Age   Salary  Country_Germany  Country_Spain
8   50  83000.0             True          False
1   27  48000.0            False           True
5   35  58000.0            False          False


In [129]:
# Step 4: Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled Training Set:")
print(X_train_scaled)
print("Scaled Test Set:")
print(X_test_scaled)


Scaled Training Set:
[[ 0.8968186   0.8892086  -0.63245553 -0.63245553]
 [ 1.6577556   1.67822469 -0.63245553 -0.63245553]
 [-1.76646088 -1.1396899   1.58113883 -0.63245553]
 [-0.43482114  0.32562569 -0.63245553 -0.63245553]
 [ 0.13588161 -0.03757219  1.58113883 -0.63245553]
 [-0.24458689 -0.35067382 -0.63245553  1.58113883]
 [-0.24458689 -1.36512307 -0.63245553  1.58113883]]
Scaled Test Set:
[[ 2.03822409  2.12909102  1.58113883 -0.63245553]
 [-2.33716363 -1.8159894  -0.63245553  1.58113883]
 [-0.81528964 -0.68882357 -0.63245553 -0.63245553]]


In [130]:
import numpy as np

# Assuming scaler is the StandardScaler instance used
means = scaler.mean_     
   # Mean of each column from the training set
scales = np.sqrt(scaler.var_)  # Standard deviation (since scaler.var_ gives variance)

# Manually compute the scaled test set values
X_test_manual_scaled = (X_test - means) / scales

# Compare with previously scaled test set
print("Scaled Test Set (from scaler):\n", X_test_scaled)
print("Manually Scaled Test Set:\n", X_test_manual_scaled)

# Check if they're close enough
print("Difference:\n", X_test_scaled - X_test_manual_scaled)


Scaled Test Set (from scaler):
 [[ 2.03822409  2.12909102  1.58113883 -0.63245553]
 [-2.33716363 -1.8159894  -0.63245553  1.58113883]
 [-0.81528964 -0.68882357 -0.63245553 -0.63245553]]
Manually Scaled Test Set:
         Age    Salary  Country_Germany  Country_Spain
8  2.038224  2.129091         1.581139      -0.632456
1 -2.337164 -1.815989        -0.632456       1.581139
5 -0.815290 -0.688824        -0.632456      -0.632456
Difference:
    Age  Salary  Country_Germany  Country_Spain
8  0.0     0.0              0.0            0.0
1  0.0     0.0              0.0            0.0
5  0.0     0.0              0.0            0.0
